-- Business tables (normalized from Superstore)

-- gen_random_uuid() is built in from Postgres 13, but the seed needs crypt()
-- anyway and an explicit extension costs nothing.
create extension if not exists pgcrypto;

create table if not exists customers (
  customer_id text primary key,
  name text not null,
  segment text not null,
  country text not null,
  city text not null,
  state text not null,
  postal_code text not null,
  region text not null
);

create table if not exists products (
  product_id text primary key,
  category text not null,
  sub_category text not null,
  name text not null
);

create table if not exists orders (
  order_id text primary key,
  customer_id text not null references customers(customer_id),
  order_date date not null,
  ship_date date not null,
  ship_mode text not null,
  region text not null,
  ship_lag_days int generated always as (ship_date - order_date) stored
);

create table if not exists order_items (
  -- The CSV import supplies its own ids ("CA-2017-152156-0"); rows created
  -- through the API have none, so the column needs a default or every insert
  -- fails on the not-null constraint.
  id text primary key default gen_random_uuid()::text,
  order_id text not null references orders(order_id),
  product_id text not null references products(product_id),
  sales numeric not null,
  quantity int not null,
  discount numeric not null,
  profit numeric not null,
  region text not null,
  category text not null
);

-- `create table if not exists` above is a no-op on a database that already has
-- the table, so retrofit the default explicitly. Safe to re-run.
alter table order_items alter column id set default gen_random_uuid()::text;

-- Platform tables (RBAC and operational)

create table if not exists roles (
  id int primary key generated by default as identity,
  key text not null unique,
  name text not null,
  is_system boolean not null default true
);

create table if not exists permissions (
  id int primary key generated by default as identity,
  module text not null,
  action text not null,
  unique(module, action)
);

create table if not exists role_permissions (
  role_id int not null references roles(id),
  permission_id int not null references permissions(id),
  primary key (role_id, permission_id)
);

create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role_id int not null references roles(id),
  scope_regions text[] not null default '{}',
  scope_categories text[] not null default '{}'
);

create index if not exists idx_profiles_scope_regions on profiles using gin (scope_regions);
create index if not exists idx_profiles_scope_categories on profiles using gin (scope_categories);

-- The row is inserted BEFORE the handler runs, so the primary key on `key` is
-- what makes two concurrent identical requests collapse into one execution.
-- `response` is therefore null until the handler finishes.
create table if not exists idempotency_keys (
  key text primary key,
  user_id uuid not null references auth.users(id),
  endpoint text not null,
  body_hash text not null,
  response jsonb,
  http_status int,
  status text not null default 'in_progress',
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists idx_idempotency_keys_user_id on idempotency_keys(user_id);
create index if not exists idx_idempotency_keys_created_at on idempotency_keys(created_at);

-- One row per user per bucket type, updated in place. Keying on window_start
-- instead would accumulate a new row every window and break the single-row read.
create table if not exists rate_limits (
  user_id uuid not null references auth.users(id),
  type text not null default 'read',
  window_start timestamptz not null default now(),
  count int not null default 0,
  primary key (user_id, type)
);

-- Collapses identical bodies sent without an Idempotency-Key inside a short
-- window — the accidental double-submit an idempotency key would have caught.
create table if not exists content_dedup (
  user_id uuid not null references auth.users(id),
  endpoint text not null,
  body_hash text not null,
  response jsonb,
  http_status int,
  status text not null default 'in_progress',
  created_at timestamptz not null default now(),
  primary key (user_id, endpoint, body_hash)
);

create index if not exists idx_content_dedup_created_at on content_dedup(created_at);

create table if not exists audit_log (
  id bigint primary key generated by default as identity,
  user_id uuid references auth.users(id),
  action text not null,
  entity text not null,
  entity_id text not null,
  before jsonb,
  after jsonb,
  at timestamp not null default now()
);

create index if not exists idx_audit_log_user_id on audit_log(user_id);
create index if not exists idx_audit_log_entity on audit_log(entity);
create index if not exists idx_audit_log_at on audit_log(at);

create table if not exists settings (
  scope text not null,
  key text not null,
  value jsonb not null,
  primary key (scope, key)
);

-- Denormalized indexes on order_items for scope filtering

create index if not exists idx_order_items_region on order_items(region);
create index if not exists idx_order_items_category on order_items(category);
create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_order_items_product_id on order_items(product_id);

-- Business table indexes

create index if not exists idx_orders_customer_id on orders(customer_id);
create index if not exists idx_orders_region on orders(region);
